
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugpnwdbrmqjtngnmuhtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVncG53ZGJybXFqdG5nbm11aHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDkxMjgsImV4cCI6MjA2MzQyNTEyOH0.a_51Nru76QLP8NYX9rtGuLtFtJv_gGEOFC4AkTWi62o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
