// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvtnccwbivpjsndzkbou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2dG5jY3diaXZwanNuZHprYm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjQ0NjEsImV4cCI6MjA2NDAwMDQ2MX0.g_qToh_le4fvGSvzimFJYNjJGv6Elt0y4laDh24_vow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);